language: java
dist: trusty
addons:
  sonarcloud:
    organization: antop-dev-github
jdk:
  - openjdk8
branches:
  only:
    - master
cache:
  directories:
    - $HOME/.m2
install:
  - ./mvnw test-compile -DskipTests=true -Dmaven.javadoc.skip=true -B -V
script:
  - ./mvnw clean test jacoco:report
after_success:
  - ./mvnw sonar:sonar -Dsonar.host.url=$SONAR_HOST_URL -Dsonar.projectKey=$SONAR_PROJECT_KEY -Dsonar.login=$SONAR_TOKEN
  - ./mvnw coveralls:report -DrepoToken=$COVERALLS_REPO_TOKEN
notifications:
  email: false
