language: java
dist: trusty
services:
  - mongodb
addons:
  sonarcloud:
    organization: antop-dev-github
jdk:
  - openjdk8
branches:
  only:
    - master
cache:
  directories:
    - $HOME/.m2
before_script:
  - sleep 15 # MongoDB does not immediately accept connections
  - mongo microservices --eval 'db.createCollection("Customers");'
script:
  - mvn test-compile -DskipTests=true -Dmaven.javadoc.skip=true -B -V
  - mvn clean test jacoco:report
after_success:
  - mvn sonar:sonar -Dsonar.host.url=$SONAR_HOST_URL -Dsonar.projectKey=$SONAR_PROJECT_KEY -Dsonar.login=$SONAR_TOKEN
  - mvn coveralls:report -DrepoToken=$COVERALLS_REPO_TOKEN
notifications:
  email: false
