# For a quick start check out our HTTP Requests collection (Tools|HTTP Client|Open HTTP Requests Collection).
#
# Following HTTP Request Live Templates are available:
# * 'gtrp' and 'gtr' create a GET request with or without query parameters;
# * 'ptr' and 'ptrp' create a POST request with a simple or parameter-like body;
# * 'mptr' and 'fptr' create a POST request to submit a form with a text or file field (multipart/form-data);

GET http://localhost:7704/functional

###

GET http://localhost:7704/functional/customer/5

###

GET http://localhost:7704/functional/customers

###

GET http://localhost:7704/functional/customers?nameFilter=in

###

POST http://localhost:7704/functional/customer
Content-Type: application/json

{
  "id": 19,
  "name": "New Customer",
  "telephone": {
    "countryCode": "+44",
    "telephoneNumber": "7123456789"
  }
}

###